"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.api.acquisitions_api import AcquisitionsApi  # noqa: E501


class TestAcquisitionsApi(unittest.TestCase):
    """AcquisitionsApi unit test stubs"""

    def setUp(self):
        self.api = AcquisitionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_acquisition_query_acquisition_acquisition_id_get(self):
        """Test case for acquisition_query_acquisition_acquisition_id_get

        Acquisition Query  # noqa: E501
        """
        pass

    def test_acquisitions_search_acquisitions_search_get(self):
        """Test case for acquisitions_search_acquisitions_search_get

        Acquisitions Search  # noqa: E501
        """
        pass

    def test_update_acquisitions_acquisition_set_update_post(self):
        """Test case for update_acquisitions_acquisition_set_update_post

        Update Acquisitions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
