"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.model.historical_last_classif import HistoricalLastClassif
globals()['HistoricalLastClassif'] = HistoricalLastClassif
from ecotaxa_cli_py.model.object_set_revert_to_history_rsp import ObjectSetRevertToHistoryRsp


class TestObjectSetRevertToHistoryRsp(unittest.TestCase):
    """ObjectSetRevertToHistoryRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectSetRevertToHistoryRsp(self):
        """Test ObjectSetRevertToHistoryRsp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectSetRevertToHistoryRsp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
