"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_py_client
from ecotaxa_py_client.model.image_model import ImageModel


class TestImageModel(unittest.TestCase):
    """ImageModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageModel(self):
        """Test ImageModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImageModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
