"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_py_client
from ecotaxa_py_client.model.user_model import UserModel


class TestUserModel(unittest.TestCase):
    """UserModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserModel(self):
        """Test UserModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
