"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.21
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.model.process_model import ProcessModel


class TestProcessModel(unittest.TestCase):
    """ProcessModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessModel(self):
        """Test ProcessModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProcessModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
