"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_py_client
from ecotaxa_py_client.model.project_taxo_stats_model import ProjectTaxoStatsModel


class TestProjectTaxoStatsModel(unittest.TestCase):
    """ProjectTaxoStatsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectTaxoStatsModel(self):
        """Test ProjectTaxoStatsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectTaxoStatsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
