"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.21
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.model.historical_classification import HistoricalClassification


class TestHistoricalClassification(unittest.TestCase):
    """HistoricalClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoricalClassification(self):
        """Test HistoricalClassification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HistoricalClassification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
