"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.21
    Generated by: https://openapi-generator.tech
"""


import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.api.taxonomy_tree_api import TaxonomyTreeApi  # noqa: E501


class TestTaxonomyTreeApi(unittest.TestCase):
    """TaxonomyTreeApi unit test stubs"""

    def setUp(self):
        self.api = TaxonomyTreeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_taxon_in_central(self):
        """Test case for add_taxon_in_central

        Add Taxon In Central  # noqa: E501
        """
        pass

    def test_get_taxon_in_central(self):
        """Test case for get_taxon_in_central

        Get Taxon In Central  # noqa: E501
        """
        pass

    def test_pull_taxa_update_from_central(self):
        """Test case for pull_taxa_update_from_central

        Pull Taxa Update From Central  # noqa: E501
        """
        pass

    def test_push_taxa_stats_in_central(self):
        """Test case for push_taxa_stats_in_central

        Push Taxa Stats In Central  # noqa: E501
        """
        pass

    def test_query_root_taxa(self):
        """Test case for query_root_taxa

        Query Root Taxa  # noqa: E501
        """
        pass

    def test_query_taxa(self):
        """Test case for query_taxa

        Query Taxa  # noqa: E501
        """
        pass

    def test_query_taxa_set(self):
        """Test case for query_taxa_set

        Query Taxa Set  # noqa: E501
        """
        pass

    def test_query_taxa_usage(self):
        """Test case for query_taxa_usage

        Query Taxa Usage  # noqa: E501
        """
        pass

    def test_reclassif_project_stats(self):
        """Test case for reclassif_project_stats

        Reclassif Project Stats  # noqa: E501
        """
        pass

    def test_reclassif_stats(self):
        """Test case for reclassif_stats

        Reclassif Stats  # noqa: E501
        """
        pass

    def test_search_taxa(self):
        """Test case for search_taxa

        Search Taxa  # noqa: E501
        """
        pass

    def test_taxa_tree_status(self):
        """Test case for taxa_tree_status

        Taxa Tree Status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
