"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_py_client
from ecotaxa_py_client.model.subset_req import SubsetReq


class TestSubsetReq(unittest.TestCase):
    """SubsetReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubsetReq(self):
        """Test SubsetReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubsetReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
