"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.21
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.model.taxon_central import TaxonCentral


class TestTaxonCentral(unittest.TestCase):
    """TaxonCentral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaxonCentral(self):
        """Test TaxonCentral"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaxonCentral()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
