"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.21
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.model.object_set_query_rsp import ObjectSetQueryRsp


class TestObjectSetQueryRsp(unittest.TestCase):
    """ObjectSetQueryRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectSetQueryRsp(self):
        """Test ObjectSetQueryRsp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectSetQueryRsp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
