"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_cli_py
from ecotaxa_cli_py.model.export_req import ExportReq


class TestExportReq(unittest.TestCase):
    """ExportReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportReq(self):
        """Test ExportReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExportReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
