"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ecotaxa_py_client
from ecotaxa_py_client.model.sample_model import SampleModel


class TestSampleModel(unittest.TestCase):
    """SampleModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSampleModel(self):
        """Test SampleModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SampleModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
