# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from ecotaxa_cli_py.configuration import Configuration


class CreateProjectReq(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'clone_of_id': 'int',
        'title': 'str',
        'visible': 'bool'
    }

    attribute_map = {
        'clone_of_id': 'clone_of_id',
        'title': 'title',
        'visible': 'visible'
    }

    def __init__(self, clone_of_id=None, title=None, visible=True, local_vars_configuration=None):  # noqa: E501
        """CreateProjectReq - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._clone_of_id = None
        self._title = None
        self._visible = None
        self.discriminator = None

        if clone_of_id is not None:
            self.clone_of_id = clone_of_id
        self.title = title
        if visible is not None:
            self.visible = visible

    @property
    def clone_of_id(self):
        """Gets the clone_of_id of this CreateProjectReq.  # noqa: E501

        If set, clone specified Project  # noqa: E501

        :return: The clone_of_id of this CreateProjectReq.  # noqa: E501
        :rtype: int
        """
        return self._clone_of_id

    @clone_of_id.setter
    def clone_of_id(self, clone_of_id):
        """Sets the clone_of_id of this CreateProjectReq.

        If set, clone specified Project  # noqa: E501

        :param clone_of_id: The clone_of_id of this CreateProjectReq.  # noqa: E501
        :type clone_of_id: int
        """

        self._clone_of_id = clone_of_id

    @property
    def title(self):
        """Gets the title of this CreateProjectReq.  # noqa: E501

        The project title  # noqa: E501

        :return: The title of this CreateProjectReq.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CreateProjectReq.

        The project title  # noqa: E501

        :param title: The title of this CreateProjectReq.  # noqa: E501
        :type title: str
        """
        if self.local_vars_configuration.client_side_validation and title is None:  # noqa: E501
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def visible(self):
        """Gets the visible of this CreateProjectReq.  # noqa: E501

        If True, the project is created visible  # noqa: E501

        :return: The visible of this CreateProjectReq.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this CreateProjectReq.

        If True, the project is created visible  # noqa: E501

        :param visible: The visible of this CreateProjectReq.  # noqa: E501
        :type visible: bool
        """

        self._visible = visible

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateProjectReq):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateProjectReq):
            return True

        return self.to_dict() != other.to_dict()
